# Makefile.mingw
#
# Description: Top Makefile for win32 (mingw) port of qrc
#

all:
	$(MAKE) -C gaym -f Makefile.mingw

install: all
	$(MAKENSIS) \
		-DGAYM_VERSION="$(GAYM_VERSION)" \
		-DGAIM_VERSION="$(GAIM_VERSION)" \
		-DGAIM_TOP="$(GAIM_TOP)" nsis/installer.nsi

clean:
	$(MAKE) -C src -f Makefile.mingw clean
	-rm *.exe
